name: reclaimify
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core & Auth
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  google_sign_in: ^7.2.0
  cloud_functions: ^6.0.5

  # State Management & Navigation
  get: ^4.6.6

  # UI & Responsive Design
  flutter_screenutil: ^5.9.0
  phosphor_flutter: ^2.0.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  pinput: ^6.0.1
  country_picker: ^2.0.24

  # Utilities
  image_picker: ^1.0.5
  url_launcher: ^6.2.2
  uuid: ^4.2.1
  shared_preferences: ^2.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  test: ^1.26.2

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/images/logo.png'

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700