services:
  - type: web
    name: external-invite-service
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: SENDGRID_API_KEY
        sync: false
      - key: SENDGRID_SENDER
        sync: false
      - key: SERVICE_ACCOUNT_JSON
        sync: false
